services:
  bolsa_gin:
    build: .
    ports:
      - "80:8081"
    env_file:
      - .env
    environment:
      - PRECIOS_BASE_URL=http://host.docker.internal:3010
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
